export const cityToTimezone = {
  "Abu Dhabi": "Asia/Dubai",
  Amsterdam: "Europe/Amsterdam",
  Ankara: "Europe/Istanbul",
  Athens: "Europe/Athens",
  Atlanta: "America/New_York",
  Auckland: "Pacific/Auckland",
  Bangkok: "Asia/Bangkok",
  Beijing: "Asia/Shanghai",
  Berlin: "Europe/Berlin",
  Bogota: "America/Bogota",
  Boston: "America/New_York",
  Brisbane: "Australia/Brisbane",
  Brussels: "Europe/Brussels",
  "Buenos Aires": "America/Argentina/Buenos_Aires",
  Cairo: "Africa/Cairo",
  "Cape Town": "Africa/Johannesburg",
  Caracas: "America/Caracas",
  Chicago: "America/Chicago",
  Copenhagen: "Europe/Copenhagen",
  Delhi: "Asia/Kolkata",
  Denver: "America/Denver",
  Dhaka: "Asia/Dhaka",
  Dubai: "Asia/Dubai",
  Dublin: "Europe/Dublin",
  Frankfurt: "Europe/Berlin",
  Geneva: "Europe/Zurich",
  "Hong Kong": "Asia/Hong_Kong",
  Honolulu: "Pacific/Honolulu",
  Houston: "America/Chicago",
  Istanbul: "Europe/Istanbul",
  Jakarta: "Asia/Jakarta",
  Johannesburg: "Africa/Johannesburg",
  Kabul: "Asia/Kabul",
  Karachi: "Asia/Karachi",
  Kiev: "Europe/Kiev",
  "Kuala Lumpur": "Asia/Kuala_Lumpur",
  Lagos: "Africa/Lagos",
  Lima: "America/Lima",
  Lisbon: "Europe/Lisbon",
  London: "Europe/London",
  "Los Angeles": "America/Los_Angeles",
  Madrid: "Europe/Madrid",
  Manila: "Asia/Manila",
  "Mexico City": "America/Mexico_City",
  Miami: "America/New_York",
  Milan: "Europe/Rome",
  Moscow: "Europe/Moscow",
  Mumbai: "Asia/Kolkata",
  Munich: "Europe/Berlin",
  Nairobi: "Africa/Nairobi",
  "New Delhi": "Asia/Kolkata",
  "New York": "America/New_York",
  Oslo: "Europe/Oslo",
  Paris: "Europe/Paris",
  Perth: "Australia/Perth",
  Prague: "Europe/Prague",
  Riyadh: "Asia/Riyadh",
  Rome: "Europe/Rome",
  "San Francisco": "America/Los_Angeles",
  Santiago: "America/Santiago",
  "Sao Paulo": "America/Sao_Paulo",
  Seoul: "Asia/Seoul",
  Shanghai: "Asia/Shanghai",
  Singapore: "Asia/Singapore",
  Stockholm: "Europe/Stockholm",
  Sydney: "Australia/Sydney",
  Taipei: "Asia/Taipei",
  Tehran: "Asia/Tehran",
  Tokyo: "Asia/Tokyo",
  Toronto: "America/Toronto",
  Vancouver: "America/Vancouver",
  Vienna: "Europe/Vienna",
  Warsaw: "Europe/Warsaw",
  Washington: "America/New_York",
  Zurich: "Europe/Zurich",
};
